### ISSUE TITLE
Support for Python 3.5

### ISSUE THREAD

**Issue by xtrntr** [timothycrosley/hypothesis-auto#3]

**Comment by mkesper** [comment]
This would have to exclude PEP526 https://docs.python.org/3/whatsnew/3.6.html#pep-526-syntax-for-variable-annotations and PEP563 https://docs.python.org/3/whatsnew/3.7.html#pep-563-postponed-evaluation-of-annotations
Python 3.6 was introduced in 2016 and Python 3.7 in 2018.
Better support modern stacks only than to waste too much energy?

**Comment by timothycrosley** [comment]
I really appreciate your work on this, but in the end, I agree with @mkesper. I intentionally don't support anything below the last release of Python for new projects. Once a project is well established I follow Python's own deprecation schedule (thus why things like isort still support 2.7). If you want (or have) to use 3.5 and want to use one of these new projects you are free to create forks that add that functionality.
