### ISSUE TITLE
Typo: Scenerio should be Scenario?

### ISSUE THREAD

**Issue by mkesper** [timothycrosley/hypothesis-auto#5]
I think that's the correct word:

> The Collaborative International Dictionary of English v.0.48 (gcide)
> Scenario Sce*na"ri*o, n. [It.]
>    A preliminary sketch of the plot, or main incidents, of an
>    opera.
>    [1913 Webster]

> 
> WordNet (r) 3.0 (2006) (wn)
> scenario
>     n 1: an outline or synopsis of a play (or, by extension, of a
>          literary work)
>     2: a setting for a work of art or literature; "the scenario is
>        France during the Reign of Terror"
>     3: a postulated sequence of possible events; "planners developed
>        several scenarios in case of an attack"

**Comment by timothycrosley** [comment]
Thanks for alerting me to this issue! I've fixed it in the 1.1.1 hotfix release.

~Timothy

**Comment by mkesper** [comment]
Thanks a lot for fast handling this! :+1:
