### ISSUE TITLE
superset of pytest-quickcheck?

### ISSUE THREAD

**Issue by sebastian-philipp** [timothycrosley/hypothesis-auto#6]
See also [pytest-quickcheck](https://pypi.org/project/pytest-quickcheck/).

If hypothesis-auto is a superset of pytest-quickcheck, it might make sense to also provide a similar interface, as having autogenerated inputs for test cases is something very useful in its own. 

Note that pytest-quickcheck's random input generation is [flawed](https://bitbucket.org/pytest-dev/pytest-quickcheck/issues/8/083-generation-of-random-lists-is-broken)

**Comment by timothycrosley** [comment]
Hi @sebastian-philipp,

If I understand correctly, I believe hypothesis itself (which will be installed if you install hypothesis-auto) provides that functionality out of the box via `given` see: https://hypothesis.readthedocs.io/en/latest/details.html?highlight=given#hypothesis.given

Let me know if there's more, beyond that, that you would like integrated that pytest-quickcheck does well.

Thanks!

~Timothy

**Comment by sebastian-philipp** [comment]
Would be cool, if *hypothesis* could use Python 3 annotations. Nevertheless, looks like I was just looking for  https://hypothesis.readthedocs.io

**Comment by timothycrosley** [comment]
> Would be cool, if hypothesis could use Python 3 annotations.

Long term plan is for hypothesis auto features to be added to hypothesis :)
